### ISSUE TITLE
Uncaught TypeError: PHPStan\Type\Doctrine\ObjectMetadataResolver::loadObjectManager()

### ISSUE THREAD

**Issue by MP-okui** [phpstan/phpstan-doctrine#131] opened 2020-06-02 06:43 UTC
> Fatal error: Uncaught TypeError: Return value of PHPStan\Type\Doctrine\ObjectMetadataResolver::loadObjectManager() must be an instance of Doctrine\Common\Persistence\ObjectManager or null, instance of Doctrine\ORM\EntityManager returned in /var/www/html/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php:69
> Stack trace:
> #0 /var/www/html/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php(55): PHPStan\Type\Doctrine\ObjectMetadataResolver->loadObjectManager('/var/www/html/t...')
> #1 /var/www/html/vendor/phpstan/phpstan-doctrine/src/Rules/Doctrine/ORM/EntityColumnRule.php(61): PHPStan\Type\Doctrine\ObjectMetadataResolver->getObjectManager()
> #2 phar:///var/www/html/vendor/phpstan/phpstan/phpstan/src/Analyser/FileAnalyser.php(69): PHPStan\Rules\Doctrine\ORM\EntityColumnRule->processNode(Object(PhpParser\Node\Stmt\PropertyProperty), Object(PHPStan\Analyser\MutatingScope))
> #3 phar:///var/www/html/vendor/phpstan/phpstan/phpstan/src/Analyser/NodeScopeResolver.php(243): PHPStan\Analy in /var/www/html/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php on line 69

- phpstan/phpstan v0.12.25
- phpstan/phpstan-doctrine ^0.12.13
- doctrine/orm v2.7.3

**Comment by ondrejmirtes** [comment] 2020-06-02 07:33
Duplicate of https://github.com/phpstan/phpstan-doctrine/issues/130

**Comment by ondrejmirtes** [comment] 2020-06-02 07:34
You can test it with phpstan-doctrine dev-master but it also needs phpstan/phpstan dev-master.

**Closed by ondrejmirtes** 2020-06-02 07:33 UTC

**Comment by MP-okui** [comment] 2020-06-02 08:38
@ondrejmirtes 

The error has been resolved. Thank you.

- phpstan/phpstan dev-master
- phpstan/phpstan-doctrine dev-master
- doctrine/orm v2.7.3
- doctrine/persistence v2.0.0
